openapi: 3.1.0
info:
  title: TrackIT Api
  version: '1.0'
  x-logo:
    url: 'https://github.com/Technova-Inc/API-TrackIT-Documentation/blob/main/track-it-logo-v1.png?raw=true'
    href: ''
servers:
  - url: 'http://10.29.126.31/api-track-it'
    description: V1 - Production
paths:
  '/Consultation?pc={nomPc}':
    parameters:
      - name: nomPc
        in: path
        required: true
        schema:
          type: integer
        description: PC ID
    get:
      summary: Récupérer informations détaillées d'un PC
      tags:
        - PC
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    default: false
                    description: If any error occurred during the request
                  pc:
                    $ref: '#/components/schemas/PcInfo'
                  software:
                    type: array
                    items:
                      $ref: '#/components/schemas/SoftwareInfo'
                  network:
                    type: array
                    items:
                      $ref: '#/components/schemas/NetworkInfo'
                required:
                  - error
        '400':
          description: Mauvaise requête - il manque le paramètre 'pc'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    default: true
                  message:
                    type: string
                    example: "Le paramètre 'pc' est requis dans l'URL."
                required:
                  - error
                  - message
        '404':
          description: PC non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    default: true
                  message:
                    type: string
                    example: "Impossible de trouver un PC avec cet identifiant."
                required:
                  - error
                  - message
      operationId: get-pc-details
      description: Récupérer des informations sur un PC, y compris son matériel, les logiciels installés et les détails du réseau.

  '/dashboard':
    get:
      summary: Récupérer les statistiques du système d'information
      tags:
        - Statistiques
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    default: false
                  windows:
                    type: integer
                    example: 15
                    description: nombre d'appareil sous Windows 
                  unix:
                    type: integer
                    example: 8
                    description: nombre d'appareil sous Unix
                  android:
                    type: integer
                    example: 5
                    description: nombre d'appareil sous Android
                required:
                  - error
                  - windows
                  - unix
                  - android
        '404':
          description: Pas de statisques trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    default: true
                  message:
                    type: string
                    example: "Aucune statistique n'a été trouvée."
                required:
                  - error
                  - message
      operationId: get-dashboard-stats
      description: Récupérer le nombre d'appareils fonctionnant sous Windows, Unix et Android.

components:
  schemas:
    PcInfo:
      type: object
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: "PC-123"
        cpu:
          type: string
          example: "Intel Core i7"
        ram:
          type: string
          example: "16GB"
        storage:
          type: string
          example: "512GB SSD"
      required:
        - id
        - name
        - cpu
        - ram
        - storage

    SoftwareInfo:
      type: object
      properties:
        name:
          type: string
          example: "Google Chrome"
        version:
          type: string
          example: "99.0.1234.56"
      required:
        - name
        - version

    NetworkInfo:
      type: object
      properties:
        ip:
          type: string
          example: "192.168.1.100"
        mac:
          type: string
          example: "00:1A:2B:3C:4D:5E"
        status:
          type: string
          example: "Connected"
      required:
        - ip
        - mac
        - status





tags:
  - name: Bienvenue!
    description: "Bienvenue sur la documentation de l'API TrackIT !"
    x-traitTag: true

